# Generated by Django 4.2.5 on 2023-09-20 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrokeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('hypertension', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('heart_disease', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('ever_married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('work_type', models.CharField(choices=[('Private', 'Private'), ('Self-employed', 'Self-employed'), ('Govt_job', 'Govt_job'), ('children', 'children'), ('Never_worked', 'Never_worked')], max_length=50)),
                ('residence_type', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=50)),
                ('avg_glucose_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('bmi', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('smoking_status', models.CharField(choices=[('formerly smoked', 'formerly smoked'), ('never smoked', 'never smoked'), ('smokes', 'smokes')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='IrisFeature',
        ),
    ]
